export interface CHESS_THEMES {
  id: string;
  name: string;
}

export const CHESS_THEMES = [
  { id: "1", name: "Fork" },
  { id: "2", name: "Mate in 1" },
//  { id: "3", name: "Mate in 2" },
//  { id: "4", name: "Mate in 3" },
//  { id: "5", name: "Mate in 4" },
//  { id: "6", name: "Mate in 5" },
//  { id: "7", name: "Mate in 6" },
  { id: "8", name: "Mate" },
  { id: "9", name: "Deflection" },
  { id: "10", name: "Advanced pawn" },
  { id: "11", name: "Sacrifice" },
  { id: "12", name: "Atraction" },
  { id: "13", name: "Middlegame" },
  { id: "14", name: "Endgame" },
  { id: "15", name: "Discovered attack" },
  { id: "16", name: "Defensive move" },
  { id: "17", name: "Exposed king" },
  { id: "18", name: "Skewer" },
//  { id: "19", name: "Kingside attack" },
//  { id: "20", name: "Queenside attack" },
  { id: "21", name: "Discovered check" },
  { id: "22", name: "Pin" },
  { id: "23", name: "Zugzwang" },
  { id: "24", name: "Opening" },
  { id: "25", name: "Hanging piece" },
  { id: "26", name: "Discovered check" },
  { id: "27", name: "enPassant" },
  { id: "28", name: "One move" },
  { id: "29", name: "Short" },
  { id: "30", name: "Long" },
  { id: "31", name: "Very long" },
  { id: "32", name: "Pawn endgame" },
  { id: "33", name: "Bishop endgame" },
  { id: "34", name: "Knight endgame" },
  { id: "35", name: "Rook endgame" },
  { id: "36", name: "Interference" },
  { id: "37", name: "Promotion" },
  { id: "38", name: "Intermezzo" },
  { id: "39", name: "Double check" },
  { id: "40", name: "Queen endgame" },
  { id: "41", name: "Queen Rook endgame" },
  { id: "42", name: "Backrank mate" },
  { id: "43", name: "Crushing" },
  { id: "44", name: "Advantage" },
  { id: "45", name: "Capturing defeneder" },
  { id: "46", name: "Trapped piece" },
  { id: "47", name: "xRay attack" },
  { id: "48", name: "Double bishop mate" },
  { id: "49", name: "Quiet mate" },
  { id: "50", name: "Master" },
  { id: "51", name: "Clearance" },
];